name = "rewild-connect"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"             # how your code refers to the DB
database_name = "rewild-db"
database_id = "local-rewild-db"   # local id now; prod id comes from CF later
